version: "2"
services:
  database:
    image: mariadb:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - backend-network
    volumes:
      - ./database:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - database

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - frontend-network

networks:
  backend-network:
    name: backend-network
  frontend-network:
    name: frontend-network
